image: ruby:2.3

pages:
  stage: deploy
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "en_US.UTF-8"
    LANGUAGE: "en_US.UTF-8"
    git:
        last_commit:
            long_sha: $CI_COMMIT_REF_SLUG
            short:sha: $CI_COMMIT_SHORT_SHA
  script:
  - gem install jekyll
  - jekyll build -d public/
  artifacts:
    paths:
    - public
  only:
  - master
