image: ruby:2.5

pages:
  stage: deploy
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "en_US.UTF-8"
    LANGUAGE: "en_US.UTF-8"
  script:
  - apt-get install imagemagick libmagickcore-dev libmagickwand-dev
  - gem install bundler
  - bundle install --deployment
  - jekyll build -d public/
  artifacts:
    paths:
    - public
  only:
  - master
