image: ruby:2.3

pages:
  stage: deploy
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "en_US.UTF-8"
    LANGUAGE: "en_US.UTF-8"
  script:
  - gem install jekyll
  - gem 'jekyll-git_metadata'
  - jekyll build -d public/
  artifacts:
    paths:
    - public
  only:
  - master
